### ISSUE TITLE
could we have an selection option to use blastp?

### ISSUE THREAD

**Issue by menchant** [crowelab/PyIR#10]
given that we have a list of protein sequences rather than nucleotide sequences in hand, could we  use blastp program for immunoglobulin protein sequence blast as it shows in igBlast website?

**Comment by reccej** [comment]
@menchant That seems like a fairly easy feature to add, I'll look into it next update!

- Sam

**Comment by sidhomj** [comment]
any updates on this feature? would be very helpful. thanks!

**Comment by crowelab** [comment]
A year late but BLASTp support will be added to the next version of PyIR -- should be pushed out in the next couple weeks as I get our Bioinformatics' guy's input on new features/germlines

**Comment by menchant** [comment]
Wow! Thanks a lot for the amazing work!

**Comment by crowelab** [comment]
BLASTp support has been added for human sequences with the protein database being supplied by our in-house bioinformaticist. Unfortunately the limit of IgBLAST functionality requires the use of the '--legacy' flag (this parses the pre-AIRR formatted output of IgBLAST), but it should still be as functional as IgBLAST. I'd love to add BLASTp support for other species as well -- if anybody has any protein BLAST germline databases to share they can be incorporated into PyIR, or people can fork this project into something more suited for their purposes.
