### ISSUE TITLE
Example PyIR output for immunarch

### ISSUE THREAD

**Issue by vadimnazarov** [crowelab/PyIR#14]
Hi, thank you for creating PyIR! Would you be open to provide an example output of PyIR so we can add it as a parsing option to https://github.com/immunomind/immunarch ? I tried to download files from Wiki, but some of them are not available, and I have troubles with the PyIR installation. So it would be great to have some PyIR outputs to quickly implement the parser and help PyIR users easily explore their AIRR data. Thank you, and let me know if you have any questions!

Issue to track the parser: immunomind/immunarch#84

-- Vadim

**Comment by reccej** [comment]
Hey Vadim,

Great to hear you're using PyIR as a part of your pipeline! I'll add more example files as time goes on, but I just uploaded one located at: [https://clonomatch.accre.vanderbilt.edu/pyirfiles/1K.json.gz]

The basic strategy for parsing the output files is to open the file and read it line-by-line, and treat each individual line as its own JSON object. Our sequencing pipeline is written largely in Python, and we handle these files generally like so:
`import gzip
import json

with gzip.open('example.json.gz', 'rt') as fin:
  for line in fin:
    obj = json.loads(line.strip())
    print(obj['sequence_id'])
`

I'll leave this issue open as a reminder to revisit the examples on our end. Thanks for asking!

- Sam
