### ISSUE TITLE
after pyir set up, pyir still can't be used with other species

### ISSUE THREAD

**Issue by kimngngoc** [crowelab/PyIR#16]
Hi,

I have been able to run pyir only on human. When I try to set up database for other species by "pyir setup" and then run pyir blast search it does not work. It always default back to human. I noticed in the pyir arg_parse.py, the choices is only for human. I tried uncommented line 175 choices=['human'] and commented the line 176 choices=['human','mouse', 'rabbit', 'rat', 'rhesus_monkey' ] but it pyir still doesn't work for any other species but human. The pyir setup command seems to run fine but it seems like there is some other arguments except the one species choices are preventing it to find the database. Any suggestion?

**Comment by crowelab** [comment]
Full support for additional species will be added in the next major update, coming in a couple weeks or so. The pyir setup script had to be rewritten to accommodate issues automatically building the germline databases

**Comment by crowelab** [comment]
Great news! PyIR now should include full support for non-human species
