### ISSUE TITLE
Add license?

### ISSUE THREAD

**Issue by dcroote** [crowelab/PyIR#17]
For those who find this repository by means other than the [BMC Bioinformatics publication](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-020-03649-5), it may be helpful to have a LICENSE file available. I see the publication has the following:

> License: Free to academics
> Any restrictions to use by non-academics: Yes; non academics should contact the author for permission to use the software or license options for incorporation into software that is being sold for profit.

**Comment by crowelab** [comment]
Great idea! License has been a part of the README for a while, but will have an official LICENSE.txt file in next major update
