### ISSUE TITLE
ABhelix data

### ISSUE THREAD

**Issue by mizraelson** [crowelab/PyIR#26]
Hi, am looking at the ABhelix derived data from your paper "High frequency of shared clonotypes in human B cell receptor repertoires". The reads corresponding to  IgA and  IgM cover a part of the C gene which is enough for isotype identification, but reads in files corresponding to IgG1-IgG4 cover only last 5 nucleotides of the C gene. I wonder how IgG1-IG4 isotypes were determined?

**Comment by crowelab** [comment]
Please email the authors of the paper for any questions about the data, I am just a developer
