### ISSUE TITLE
I get an empty output json when running blastp on TCR data.

### ISSUE THREAD

**Issue by nickrrose** [crowelab/PyIR#27]
These are my args
'--species', 'human', '-r', 'TCR', '--legacy', '--sequence_type','prot'

when I reverse translate any given sequence into nucleotides and run it under the nucl flag, I get a correct output.

**Comment by Ch-rode** [comment]
hi ! I have exactly the same issue. Did you solve it in someway? this could save my day ! thanks

**Comment by myersml5** [comment]
Chiara, did you run the database setup stage (#3 in the readme) and did it give you any error messages? @Ch-rode 

Sam, do you think this is related to database setup failing because IMGT no longer accepts HTTPS? @reccej 
@Ch-rode

**Comment by Ch-rode** [comment]
Thanks @myersml5. Yes, I think my problem when I run` pyir setup` is related to the same issue from #29. I have the following error message and the database is only partially constructed. 
`line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>
`

**Comment by reccej** [comment]
Marking this issue as closed because its not a real issue; you need to run the PyIR setup script before processing the sequences. See step 3 of the installation instructions.

@Ch-rode I'll tag you in issue #29, but that one has been fixed as well
