### ISSUE TITLE
Allow argument for setting IGBlast word size

### ISSUE THREAD

**Issue by velcrospud** [crowelab/PyIR#7]
This publication suggests that the default IGBlast word_size (9) is already too high, and PyIR is hardcoded to 11.

I'm running into real data where this is causing errors.

Please consider adding an argument that would allow users to set their desired word_size.

http://simlab.biomed.drexel.edu/papers_published/discrimination_zhang_2015.pdf

**Comment by tjonesster** [comment]
-wordsize argument has been added to pyir. It will just pass whatever you hand it to the igblast executable. We also made it so that penalty, reward and a couple other similar properties can be set in pyir in the same way.

**Comment by tjonesster** [comment]
I'm gonna close this issue since a fix has been deployed. Thanks for bringing it up.

**Comment by velcrospud** [comment]
Awesome!  Thanks for the prompt response.  I really like Pyir.
