### ISSUE TITLE
missing FR4 with PyIR 1.3 AIRR parser

### ISSUE THREAD

**Issue by liukai1029** [crowelab/PyIR#9]
Hi PyIR team,

With PyIR 1.3, we have noticed that many queries/alignments are missing FR4. A closer look indicates that many sequences do contain the FR4 but not being reported in PyIR 1.3. 

Below is one example annotated by PyIR 1.0 and PyIR 1.3 respectively; only minimal information included to reproduce behavior; PyIR 1.0 results has proper end of FR4 and agrees much better with Igblast web tool.

**PyIR 1.0**
    "Raw Sequence":"CAACATCCGAGCAGGGTTATCTGGTCTGATGGCTCAAACACAGCGACCTCGGGTGGGAACACGTTTTTCAGGTCCTCTGTGACCGTGAGCCTGGTGCCCGGCCCGAAGTACTGCTCGTAGGATTCCAACCCCCACTCCCATCTAGCACTGCAGATGTAGAAGCTGCTGTCTTCAGGATGGGCACTGGTCACTGTCAGAGTGGACAAGGTCAGGCTTGCATGGTTGATGAGAAACTTGTCCTTCTCGACGCCTTGCTCGTATGTGGCCTTGGAGCCCTCATTGGAAGTTGCCATCAGCATGAGACTCTGTTTCGGGAACTGACGATACCAAAACATAGTTGTGGCCTGAAAGTCCAGGGAACGGCACTCGATCTTCACAGAGGTTCCACTCTTACAGATAACCCTGCTCGGATGTTGAGAGACGACAGCACCAAGCCCGGAGCCTGGCCCCAGAAGCAGCAGAAGCAGCAGCATCTTCCGTGATGGCCTCACACCACCTTCTCTGGGGAGAGTTCAGAGCGCAGAGC",
"CDR1":{
        "from":174.0,
        "to":191.0,
        "length":18.0,
        "matches":18.0,
        "mismatches":0.0,
        "gaps":0.0,
        "percent identity":100.0,
        "AA":"DFQATT",
        "NT":"GACTTTCAGGCCACAACT"
    },
    "FR2":{
        "from":192.0,
        "to":242.0,
        "length":51.0,
        "matches":51.0,
        "mismatches":0.0,
        "gaps":0.0,
        "percent identity":100.0,
        "AA":"MFWYRQFPKQSLMLMAT",
        "NT":"ATGTTTTGGTATCGTCAGTTCCCGAAACAGAGTCTCATGCTGATGGCAACT"
    },
    "CDR2":{
        "from":243.0,
        "to":263.0,
        "length":21.0,
        "matches":21.0,
        "mismatches":0.0,
        "gaps":0.0,
        "percent identity":100.0,
        "AA":"SNEGSKA",
        "NT":"TCCAATGAGGGCTCCAAGGCC"
    },
    "FR3":{
        "from":264.0,
        "to":377.0,
        "length":114.0,
        "matches":114.0,
        "mismatches":0.0,
        "gaps":0.0,
        "percent identity":100.0,
        "AA":"TYEQGVEKDKFLINHASLTLSTLTVTSAHPEDSSFYIC",
        "NT":"ACATACGAGCAAGGCGTCGAGAAGGACAAGTTTCTCATCAACCATGCAAGCCTGACCTTGTCCACTCTGACAGTGACCAGTGCCCATCCTGAAGACAGCAGCTTCTACATCTGC"
    },
    "CDR3":{
        "from":378.0,
        "to":386.0,
        "length":9.0,
        "matches":9.0,
        "mismatches":0.0,
        "gaps":0.0,
        "percent identity":100.0,
        "AA":"SARWEWGLESYEQY",
        "NT":"AGTGCTAGATGGGAGTGGGGGTTGGAATCCTACGAGCAGTAC"
"FR4":{
        "AA":"FGPGTRLTVT",
        "NT":"TTCGGGCCGGGCACCAGGCTCACGGTCACAG"

**PyIR 1.3 :**    

"sequence":"GCTCTGCGCTCTGAACTCTCCCCAGAGAAGGTGGTGTGAGGCCATCACGGAAGATGCTGCTGCTTCTGCTGCTTCTGGGGCCAGGCTCCGGGCTTGGTGCTGTCGTCTCTCAACATCCGAGCAGGGTTATCTGTAAGAGTGGAACCTCTGTGAAGATCGAGTGCCGTTCCCTGGACTTTCAGGCCACAACTATGTTTTGGTATCGTCAGTTCCCGAAACAGAGTCTCATGCTGATGGCAACTTCCAATGAGGGCTCCAAGGCCACATACGAGCAAGGCGTCGAGAAGGACAAGTTTCTCATCAACCATGCAAGCCTGACCTTGTCCACTCTGACAGTGACCAGTGCCCATCCTGAAGACAGCAGCTTCTACATCTGCAGTGCTAGATGGGAGTGGGGGTTGGAATCCTACGAGCAGTACTTCGGGCCGGGCACCAGGCTCACGGTCACAGAGGACCTGAAAAACGTGTTCCCACCCGAGGTCGCTGTGTTTGAGCCATCAGACCAGATAACCCTGCTCGGATGTTG",
 "fwr1":"GGTGCTGTCGTCTCTCAACATCCGAGCAGGGTTATCTGTAAGAGTGGAACCTCTGTGAAGATCGAGTGCCGTTCCCTG",
    "fwr1_aa":"GAVVSQHPSRVICKSGTSVKIECRSL",
    "cdr1":"GACTTTCAGGCCACAACT",
    "cdr1_aa":"DFQATT",
    "fwr2":"ATGTTTTGGTATCGTCAGTTCCCGAAACAGAGTCTCATGCTGATGGCAACT",
    "fwr2_aa":"MFWYRQFPKQSLMLMAT",
    "cdr2":"TCCAATGAGGGCTCCAAGGCC",
    "cdr2_aa":"SNEGSKA",
    "fwr3":"ACATACGAGCAAGGCGTCGAGAAGGACAAGTTTCTCATCAACCATGCAAGCCTGACCTTGTCCACTCTGACAGTGACCAGTGCCCATCCTGAAGACAGCAGCTTCTACATCTGC",
    "fwr3_aa":"TYEQGVEKDKFLINHASLTLSTLTVTSAHPEDSSFYIC",
    "fwr4":"",
    "fwr4_aa":"",
    "cdr3":"AGTGCTAGATGGGAGTGGGGGTTGGAATCCTACGAGCAGTAC",
    "cdr3_aa":"SARWEWGLESYEQY",
  
UPDATE: A closer look tells me that this is only relating to igblast's AIRR output parser. The legacy parser is still as good but doesn't support tsv outfmt. It will be nice to have the AIRR parser return FR4.

**Comment by reccej** [comment]
Hey @liukai1029,

Thanks for bringing this to my attention, I tried running your example sequences but it wasn't able to parse a lot of information out, perhaps they're too truncated? Regardless, I'm taking a look & figuring out how best to solve the problem, especially if it's directly related to the output method from IgBLAST.
